name: "DEV Deploy"

on:
    push:
        branches:
            - develop

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: dev
            aws-region: "us-east-1"
            aws-statefile-s3-bucket: "tf-s3-robelio-001"
            aws-lock-dynamodb-table: "tf-dynamo-robelio-001"